=== evanhantman/CardLists/schemas/release.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "nonEmptyString": {
      "type": "string",
      "pattern": "^\\S(.*\\S)?$"
    },
    "versionString": {
      "type": "string",
      "pattern": "^[0-9]+\\.[0-9]+$"
    },
    "uuid": {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    },
    "oddsString": {
      "type": "string",
      "pattern": "^[0-9]+:[0-9,]+$"
    },
    "productOdds": {
      "type": "object",
      "properties": {
        "product": { "type": "string" },
        "odds": { "$ref": "#/definitions/oddsString" }
      },
      "required": [
        "product",
        "odds"
      ]
    },
    "attributeNotePair": {
      "type": "object",
      "properties": {
        "attribute": { "$ref": "#/definitions/nonEmptyString" },
        "note": { "$ref": "#/definitions/nonEmptyString" }
      },
      "required": [
        "attribute",
        "note"
      ]
    },
    "variation": {
      "type": "object",
      "properties": {
        "variation": { "$ref": "#/definitions/nonEmptyString" },
        "note": { "$ref": "#/definitions/nonEmptyString" },
        "insertOdds": {
          "type": "array",
          "items": { "$ref": "#/definitions/productOdds" }
        },
        "parallels": {
          "type": "array",
          "items": { "$ref": "#/definitions/parallel" }
        },
        "attributes": {
          "type": "array",
          "items": { "$ref": "#/definitions/nonEmptyString" }
        },
        "numberedTo": {
          "type": "integer",
          "minimum": 1
        }
      },
      "required": [
        "variation"
      ]
    },
    "parallel": {
      "type": "object",
      "properties": {
        "name": { "$ref": "#/definitions/nonEmptyString" },
        "numberedTo": {
          "type": "integer",
          "minimum": 1
        },
        "notes": {
          "type": "array",
          "items": { "$ref": "#/definitions/nonEmptyString" }
        },
        "insertOdds": {
          "type": "array",
          "items": { "$ref": "#/definitions/productOdds" }
        }
      },
      "required": [
        "name"
      ]
    },
    "card": {
      "type": "object",
      "properties": {
        "uniqueId": { "$ref": "#/definitions/uuid" },
        "number": {
          "type": "string",
          "pattern": "^[a-zA-Z0-9 .-]*$"
        },
        "name": { "$ref": "#/definitions/nonEmptyString" },
        "attributes": {
          "type": "array",
          "items": { "$ref": "#/definitions/nonEmptyString" }
        },
        "insertOdds": {
          "type": "array",
          "items": { "$ref": "#/definitions/productOdds" }
        },
        "note": { "$ref": "#/definitions/nonEmptyString" },
        "variations": {
          "type": "array",
          "items": { "$ref": "#/definitions/variation" }
        },
        "parallels": {
          "type": "array",
          "items": { "$ref": "#/definitions/parallel" }
        }
      },
      "required": [
        "uniqueId",
        "name"
      ]
    },
    "set": {
      "type": "object",
      "properties": {
        "uniqueId": { "$ref": "#/definitions/uuid" },
        "name": { "$ref": "#/definitions/nonEmptyString" },
        "notes": {
          "type": "array",
          "items": { "$ref": "#/definitions/nonEmptyString" }
        },
        "numberedTo": {
          "type": "integer",
          "minimum": 1
        },
        "insertOdds": {
          "type": "array",
          "items": { "$ref": "#/definitions/productOdds" }
        },
        "variations": {
          "type": "array",
          "items": { "$ref": "#/definitions/variation" }
        },
        "parallels": {
          "type": "array",
          "items": { "$ref": "#/definitions/parallel" }
        },
        "cards": {
          "type": "array",
          "items": { "$ref": "#/definitions/card" }
        }
      },
      "required": [
        "uniqueId",
        "name",
        "cards"
      ]
    }
  },
  "type": "object",
  "properties": {
    "name": { "$ref": "#/definitions/nonEmptyString" },
    "version": { "$ref": "#/definitions/versionString" },
    "uniqueId": { "$ref": "#/definitions/uuid" },
    "attributes": {
      "type": "array",
      "items": { "$ref": "#/definitions/attributeNotePair" }
    },
    "notes": {
      "type": "array",
      "items": { "$ref": "#/definitions/nonEmptyString" }
    },
    "sets": {
      "type": "array",
      "items": { "$ref": "#/definitions/set" }
    }
  },
  "required": [
    "name",
    "version",
    "uniqueId",
    "sets"
  ]
}

=== evanhantman/CardLists/categories/baseball/2000/2000-Topps.json
{
    "$schema": "https://raw.githubusercontent.com/JunkWaxData/CardLists/refs/heads/main/schemas/release.json",
    "name": "2000 Topps Baseball",
    "version": "1.0",
    "uniqueId": "210466d8-3df6-46ea-8ae7-dab4108066d0",
    "attributes": [
        {
            "attribute": "ASR",
            "note": "All-Star Rookie"
        },
        {
            "attribute": "RC",
            "note": "Rookie Card"
        },
        {
            "attribute": "LL",
            "note": "League Leaders"
        },
        {
            "attribute": "DPK",
            "note": "Draft Pick"
        },
        {
            "attribute": "PROS",
            "note": "Prospect"
        },
        {
            "attribute": "UER",
            "note": "Uncorrected Error"
        },
        {
            "attribute": "SH",
            "note": "Season Highlights"
        },
        {
            "attribute": "WS",
            "note": "World Series"
        },
        {
            "attribute": "AU",
            "note": "Autograph"
        },
        {
            "attribute": "RELIC",
            "note": "Relic Card"
        },
        {
            "attribute": "EXCH",
            "note": "Exchange Card"
        },
        {
        
            "attribute": "ALDS",
            "note": "American League Division Series"
        },
        {
            "attribute": "NLDS",
            "note": "National League Division Series"
        },
        {
            "attribute": "ALCS",
            "note": "American League Championship Series"
        },
        {
            "attribute": "NLCS",
            "note": "National League Championship Series"
        },
        {
            "attribute": "WS",
            "note": "World Series"
        }
    ],
    "sets": [
        {
            "name": "Series 1",
            "parallels": [
                {
                    "name": "Limited Edition",
                    "notes": [
                        "Distributed as a Factory Set"
                    ]
                }
            ],
            "cards": [
                {
                    "number": "1",
                    "name": "Mark McGwire",
                    "uniqueId": "fc066dcc-19ec-4e10-ae36-3deeb805e85e"
                },
                {
                    "number": "2",
                    "name": "Tony Gwynn",
                    "uniqueId": "b2216cf9-d016-4961-b456-dad84adb934d"
                },
                {
                    "number": "3",
                    "name": "Wade Boggs",
                    "uniqueId": "feb9157b-ddf3-4ffb-ba45-d526353d7788"
                },
                {
                    "number": "4",
                    "name": "Cal Ripken",
                    "uniqueId": "5924d096-bca4-4885-a83b-c864408b931e"
                },
                {
                    "number": "5",
                    "name": "Matt Williams",
                    "uniqueId": "93ca4c37-4c0d-4e6b-bbc7-c6ce804e389a"
                },
                {
                    "number": "6",
                    "name": "Jay Buhner",
                    "uniqueId": "24a0cc6b-446f-4916-aebf-0012f0d7ec4e"
                },
                {
                    "number": "8",
                    "name": "Jeff Conine",
                    "uniqueId": "2ed76938-1038-4ad2-9e72-8727f3987b4f"
                },
                {
                    "number": "9",
                    "name": "Todd Greene",
                    "uniqueId": "57f403a5-8028-42bf-9090-eb17bd7d81c4"
                },
                {
                    "number": "10",
                    "name": "Mike Lieberthal",
                    "uniqueId": "543a9000-a513-46d9-a26e-46af82fbc41d"
                },
                {
                    "number": "11",
                    "name": "Steve Avery",
                    "uniqueId": "a6030ac8-f666-4fe0-a503-f45e7bd79472"
                },
                {
                    "number": "12",
                    "name": "Bret Saberhagen",
                    "uniqueId": "9409a003-1f92-4126-9bca-d3e371b77eab"
                },
                {
                    "number": "13",
                    "name": "Magglio Ordonez",
                    "uniqueId": "c7e1bf1a-71ea-4980-9fa7-169a21693f7d"
                },
                {
                    "number": "14",
                    "name": "Brad Radke",
                    "uniqueId": "06faf7dd-17f2-49dc-a51e-51e4f3af97d3"
                },
                {
                    "number": "15",
                    "name": "Derek Jeter",
                    "uniqueId": "61650f13-e7a4-4e3e-ad47-6aa69508a45d"
                },
                {
                    "number": "16",
                    "name": "Javy Lopez",
                    "uniqueId": "ed361ca9-bfb4-4f93-b700-06ad3bee8ae3"
                },
                {
                    "number": "17",
                    "name": "Russ Davis",
                    "uniqueId": "4281c37c-4b87-4f89-a67d-cdea8b1b40c4"
                },
                {
                    "number": "18",
                    "name": "Armando Benitez",
                    "uniqueId": "f8572a28-824c-453d-b246-d209df0c1a8f"
                },
                {
                    "number": "19",
                    "name": "B.J. Surhoff",
                    "uniqueId": "e03c9134-c913-401f-b8ec-e6b7476aa018"
                },
                {
                    "number": "20",
                    "name": "Darryl Kile",
                    "uniqueId": "6f71033b-b9ff-48b0-ac38-7ee72911fbc7"
                },
                {
                    "number": "21",
                    "name": "Mark Lewis",
                    "uniqueId": "a85cfdf8-e386-410f-baab-4a58d94febde"
                },
                {
                    "number": "22",
                    "name": "Mike Williams",
                    "uniqueId": "14ce5643-2709-40df-a185-24e40cceec12"
                },
                {
                    "number": "23",
                    "name": "Mark McLemore",
                    "uniqueId": "fce4f9d4-5132-4a1e-b037-3b586d565af2"
                },
                {
                    "number": "24",
                    "name": "Sterling Hitchcock",
                    "uniqueId": "90ee8a25-4d67-453b-b08f-6f36388eea4d"
                },
                {
                    "number": "25",
                    "name": "Darin Erstad",
                    "uniqueId": "70eb1918-48fa-4ec1-87a5-442ef60b8177"
                },
                {
                    "number": "26",
                    "name": "Ricky Gutierrez",
                    "uniqueId": "44f11629-ad18-47c2-b828-dee2393d4406"
                },
                {
                    "number": "27",
                    "name": "John Jaha",
                    "uniqueId": "baed726e-36c9-4793-9ccd-cc6762368582"
                },
                {
                    "number": "28",
                    "name": "Homer Bush",
                    "uniqueId": "dbe87532-393c-4ce0-a7bd-79f98fb4b03d"
                },
                {
                    "number": "29",
                    "name": "Darrin Fletcher",
                    "uniqueId": "387a9c76-dcbd-4463-ae19-80fde66a2ead"
                },
                {
                    "number": "30",
                    "name": "Mark Grace",
                    "uniqueId": "e4647a06-2c95-4d84-9e07-10ef1f500265"
                },
                {
                    "number": "31",
                    "name": "Fred McGriff",
                    "uniqueId": "531061d3-43eb-4840-bf6d-5c0f4f51620b"
                },
                {
                    "number": "32",
                    "name": "Omar Daal",
                    "uniqueId": "f8f1dbf8-50b9-402d-8552-d0a864fc94cb"
                },
                {
                    "number": "33",
                    "name": "Eric Karros",
                    "uniqueId": "a046c083-315a-40ab-bcc8-8facf14c497c"
                },
                {
                    "number": "34",
                    "name": "Orlando Cabrera",
                    "uniqueId": "663d763a-57b3-43b1-b09b-34bab52e52f8"
                },
                {
                    "number": "35",
                    "name": "J.T. Snow Jr.",
                    "uniqueId": "5a977a8b-c739-4b30-86d7-c404d71e8eb4"
                },
                {
                    "number": "36",
                    "name": "Luis Castillo",
                    "uniqueId": "463c954e-fe46-41e2-a1eb-e693b810f854"
                },
                {
                    "number": "37",
                    "name": "Rey Ordonez",
                    "uniqueId": "65895fce-6e72-4033-939a-3e1e49c5c1f2"
                },
                {
                    "number": "38",
                    "name": "Bob Abreu",
                    "uniqueId": "8bf08112-70de-4bdd-a461-6f1f22ed30cc"
                },
                {
                    "number": "39",
                    "name": "Warren Morris",
                    "attributes": [
                        "ASR"
                    ],
                    "uniqueId": "59676f3d-eb65-48fa-a657-77fdff1a5683"
                },
                {
                    "number": "40",
                    "name": "Juan Gonzalez",
                    "uniqueId": "205cfefc-4430-4677-81a5-1f85ded35e94"
                },
                {
                    "number": "41",
                    "name": "Mike Lansing",
                    "uniqueId": "1562d3d6-b1f5-4e45-b5e9-0cf51901bf0d"
                },
                {
                    "number": "42",
                    "name": "Chili Davis",
                    "uniqueId": "2a5c482c-49c3-4686-bd4c-2f4aec524350"
                },
                {
                    "number": "43",
                    "name": "Dean Palmer",
